add php.script, etc/php.d, redis.ini

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,46 +1,51 @@
 #!/bin/sh
 
-NETSCAN_ROOT=`dirname "${0}"`/..
-cd "${NETSCAN_ROOT}" || exit 1
-NETSCAN_ROOT=`readlink -f "${NETSCAN_ROOT}"`
+LNMP_ROOT=`dirname "${0}"`/..
+cd "${LNMP_ROOT}" || exit 1
+LNMP_ROOT=`readlink -f "${LNMP_ROOT}"`
 
 PHPFPM_CONTROL=bin/phpfpm_control
 NGINX_CONTROL=bin/nginx_control
 
-netscan_help(){
+lnmp_help(){
     echo "${0} <start|stop|restart>"
     exit 1
 }
 
-netscan_start(){
+lnmp_start(){
     ${PHPFPM_CONTROL} start && ${NGINX_CONTROL} start
     return $?
 }
 
-netscan_stop(){
+lnmp_stop(){
     ${PHPFPM_CONTROL} stop && ${NGINX_CONTROL} stop
     return $?
 }
 
-netscan_restart(){
-    netscan_stop && netscan_start
+lnmp_reload(){
+    ${PHPFPM_CONTROL} reload && ${NGINX_CONTROL} reload
+    return $?
+}
+
+lnmp_restart(){
+    lnmp_stop && lnmp_start
     return $?
 }
 
 case "${1}" in
-    start|stop|restart)
-        "netscan_${1}"
+    start|stop|restart|reload)
+        "lnmp_${1}"
         ;;
     *)
-        netscan_help
+        lnmp_help
         ;;
 esac
 
 if [ $? -ne 0 ]; then
-    echo "[FAIL] ${1}" 1>&2
+    echo "[FAIL] all ${1}" 1>&2
     exit 1
 fi
 
-echo "[OK] ${1}"
+echo "[OK] all ${1}"
 exit 0
 
diff --git a/bin/nginx_control b/bin/nginx_control
--- a/bin/nginx_control
+++ b/bin/nginx_control
@@ -5,6 +5,8 @@ cd "${NGINX_ROOT}" || exit 1
 NGINX_ROOT=`readlink -f "${NGINX_ROOT}"`
 
 NGINX_CONF=etc/nginx.conf
+NGINX_PIDFILE=run/nginx.pid
+NGINX_PROC_NAME=nginx
 NGINX="./sbin/nginx -p . -c ${NGINX_CONF}"
 
 
@@ -13,12 +15,30 @@ nginx_help(){
     exit 1
 }
 
+nginx_checkhealth(){
+    [ -e "${NGINX_PIDFILE}" ] || return 1
+    PID=`cat "${NGINX_PIDFILE}" 2>/dev/null`
+    [ $? = 0 ] || return 1
+    ps --pid ${PID} |grep ${NGINX_PROC_NAME} &>/dev/null || return 1
+    return 0
+}
+
 nginx_start(){
+    nginx_checkhealth
+    if [ $? = 0 ]; then
+        echo "[WARN] nginx is already running!" 1>&2
+        return 0
+    fi
     ${NGINX}
     return $?
 }
 
 nginx_stop(){
+    nginx_checkhealth
+    if [ $? != 0 ]; then
+        echo "[WARN] nginx is not running!" 1>&2
+        return 0
+    fi
     ${NGINX} -s stop
     return $?
 }
@@ -43,10 +63,10 @@ case "${1}" in
 esac
 
 if [ $? -ne 0 ]; then
-    echo "[FAIL] ${1}" 1>&2
+    echo "[FAIL] nginx ${1}" 1>&2
     exit 1
 fi
 
-echo "[OK] ${1}"
+echo "[OK] nginx ${1}"
 exit 0
 
diff --git a/bin/phpfpm_control b/bin/phpfpm_control
--- a/bin/phpfpm_control
+++ b/bin/phpfpm_control
@@ -7,44 +7,68 @@ PHPFPM_ROOT=`readlink -f "${PHPFPM_ROOT}"`
 PHPFPM_CONF=etc/php-fpm.conf
 PHPINI_CONF=etc/php.ini
 PHPFPM_PID=logs/php-fpm.pid
+EXTENSION_DIR=lib/php/extensions/no-debug-non-zts-20100525
+PHPFPM_PROC_NAME=php-fpm
+PHP_CONF_DIR=etc/php.d
 PHPFPM="./sbin/php-fpm -p . -c ${PHPINI_CONF} -y ${PHPFPM_CONF} -D -g ${PHPFPM_PID}"
-
 
 phpfpm_help(){
     echo "${0} <start|stop|restart>"
     exit 1
 }
 
+init_extension_conf(){
+    [ -e "${PHP_CONF_DIR}" ] || mkdir -p "${PHP_CONF_DIR}"
+    EXTENSION_CONF=${PHP_CONF_DIR}/extension_dir.ini
+    EXTENSION_LIB=`readlink -f "${EXTENSION_DIR}"`
+    EXTENSION_CONF_CONTENTS="extension_dir=\"${EXTENSION_LIB}\""
+
+    CONF_MD5=`md5sum "${EXTENSION_CONF}" 2>/dev/null |awk '{print $1}'`
+    STR_MD5=`echo "${EXTENSION_CONF_CONTENTS}" |md5sum |awk '{print $1}'`
+
+    [ "${CONF_MD5}" = "${STR_MD5}" ] || echo "${EXTENSION_CONF_CONTENTS}" >${EXTENSION_CONF}
+}
+
+phpfpm_checkhealth(){
+    [ -e "${PHPFPM_PID}" ] || return 1
+    PID=`cat "${PHPFPM_PID}" 2>/dev/null`
+    [ $? = 0 ] || return 1
+    ps --pid ${PID} |grep ${PHPFPM_PROC_NAME} &>/dev/null || return 1
+    return 0
+}
+
 phpfpm_start(){
+    init_extension_conf
+    phpfpm_checkhealth
+    if [ $? = 0 ]; then
+        echo "[WARN] php-fpm is aleady running!"
+        return 0
+    fi
     ${PHPFPM}
     return $?
 }
 
 phpfpm_stop(){
-    PID=`cat "${PHPFPM_PID}"`
+    phpfpm_checkhealth
     if [ $? != 0 ]; then
-        echo "${PHPFPM_PID} is not exists"
-        return 0
-    fi
-    ps --pid "${PID}" &>/dev/null
-    if [ $? != 0 ]; then
-        echo "php-fpm is not running"
+        echo "[WARN] php-fpm is not running!"
         return 0
     fi
     kill "${PID}"
     if [ $? != 0 ]; then
-        echo "kill ${PID} failed"
+        echo "[FAIL] kill ${PID} failed"
         return $?
     fi
     sleep 1
-    ps --pid "${PID}" &>/dev/null
+
+    phpfpm_checkhealth
     if [ $? = 0 ]; then
-        echo "php-fpm is still running, kill -9 php-fpm"
+        echo "[WARN] php-fpm is still running, kill -9 php-fpm"
         kill -9 "${PID}"
         sleep 1
-        ps --pid "${PID}" &>/dev/null
+        phpfpm_checkhealth
         if [ $? = 0 ]; then
-            echo "kill -9 php-fpm failed"
+            echo "[WARN] kill -9 php-fpm failed"
             return 1
         fi
     fi
@@ -56,8 +80,19 @@ phpfpm_restart(){
     return $?
 }
 
+phpfpm_reload(){
+    phpfpm_checkhealth
+    if [ $? != 0 ]; then
+        echo "[FAIL] php-fpm is not running!"
+        return 1
+    fi
+    PID=`cat "${PHPFPM_PID}"`
+    kill -USR1 "${PID}"
+    return $?
+}
+
 case "${1}" in
-    start|stop|restart)
+    start|stop|restart|reload)
         "phpfpm_${1}"
         ;;
     *)
